.TH blt vcf-search 1

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na
blt vcf-search chromosome position < file.seq
.ad
.fi

.SH DESCRIPTION

.B blt vcf-search
locates a given chromosome and position within a VCF file.

.SH EXAMPLES
.nf
.na
blt vcf-search chr1 234234 < file.vcf
.ad
.fi

.SH SEE ALSO

blt(1)

.SH AUTHOR
.nf
.na
J. Bacon
