.TH blt\ ensemblid2gene 1

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na
blt ensemblid2gene file.gff3 ids.txt > ids-and-gene-names.tsv
.ad
.fi

.SH DESCRIPTION

.B blt ensemblid2gene
reads a list of Ensembl IDs, one per line, and outputs them along with
their associated gene name, in TSV (tab-separated-values) format.

.SH EXAMPLES
.nf
.na
blt ensemblid2gene file.gff3 ids.txt > ids-and-gene-names.tsv
.ad
.fi

.SH SEE ALSO

blt(1)

.SH AUTHOR
.nf
.na
J. Bacon
