.TH blt vcf-search 1

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na
blt gff-to-bed < file.gff3 > file.bed
.ad
.fi

.SH DESCRIPTION

.B blt gff-to-fasta
converts GFF3 input to BED output.  Currently it generates 6-column BED
output with scores set to 0.

.SH EXAMPLES
.nf
.na
blt < file.gff3 > file.bed
.ad
.fi

.SH SEE ALSO

blt(1)

.SH AUTHOR
.nf
.na
J. Bacon
