.TH blt fastx2tsv 1
.SH NAME    \" Section header
.PP

blt fastx2tsv - Convert FASTA and FASTQ streams to TSV format

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na 
blt fastx2tsv < file.fastq > file.tsv
blt fastx2tsv < file.fasta > file.tsv
.ad
.fi

.SH "DESCRIPTION"
.B blt fastx2tsv
converts a FASTA or FASTQ stream, possibly containing wrapped sequences and
phred scores,
into tab-separated data (TSV) for easier processing using standard tools
such as awk, cut, etc.  The TSV output of processing can be converted back to
FASTA or FASTQ format using awk as follows:

.nf
.na
awk -F '\\t' '{ printf("%s\\n%s\\n", $1, $2); }' \\
    file.tsv > file.fasta
awk -F '\\t' '{ printf("%s\\n%s\\n%s\\n%s\\n", $1, $2, $3, $4); }' \\
    file.tsv > file.fastq
.ad
.fi

.SH "EXAMPLES"
.nf
.na
# Filter a FASTA file for sequences containing a pattern
blt fastx2tsv < file.fasta | \\
    awk -F '\\t' '$2 ~ "ATTACGTAAC" { printf("%s\\n%s\\n", $1, $2); }' \\
    > filtered.fasta
.ad
.fi

.SH "SEE ALSO"
blt-fastx-derep(1), blt-fastq-derep.sh(1)

.SH AUTHOR
.nf
.na
J. Bacon
