.TH fastx-derep 1

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na
fastx-derep < file.fastq > file-uniq.fastq
.ad
.fi

.SH DESCRIPTION

Remove replicates from a FASTA or FASTQ file by hashing each sequence and
printing
only records for which the hash has not previously been encountered.

If memory is a limiting factor for your dereplication jobs, see
fastq-derep.sh(3), a shell script utilizing the Unix sort command, which
automatically breaks large files into chunks so they can be sorted within
available memory.  fastq-derep.sh is much slower, but may be able to
complete tasks where other methods run out of memory.

.SH EXAMPLES
.nf
.na
fastx-derep < file.fasta > file-uniq.fasta
xzcat file.fasta.xz | fastx-derep > file-uniq.fasta
xzcat file.fastq.xz | fastx-derep > file-uniq.fastq
.ad
.fi

.SH SEE ALSO

fastx2tsv(1), fastq-derep.sh(1)

.SH AUTHOR
.nf
.na
J. Bacon
