.TH fastq2tsv 1
.SH NAME    \" Section header
.PP

fastq2tsv - Convert FASTQ file to TSV format

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na 
fastq2tsv < file.fastq > file.tsv
.ad
.fi

.SH "DESCRIPTION"
.B fastq2tsv
converts a FASTQ file, possibly containing wrapped sequences and phred scores,
into tab-separated data (TSV) for easier processing using standard tools
such as awk, cut, etc.  The TSV output of processing can be converted back to
FASTQ format using awk as follows:

.nf
.na
awk -F "\t" '{ printf("%s\n%s\n%s\n%s\n", $1, $2, $3, $4); }' file.tsv \\
    processed-file.fasta
.ad
.fi

.SH "SEE ALSO"
fastq-derep

.SH BUGS
Please report bugs to the author and send patches in unified diff format.
(man diff for more information)

.SH AUTHOR
.nf
.na
J. Bacon
