.TH fastq-derep 1

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na
fastq-derep < file.fastq > file-uniq.fastq
xzcat file.fastq.xz | fastq-derep > file-uniq.fastq
.ad
.fi

.SH DESCRIPTION

Remove replicates from a fastq file by hashing each sequence and printing
only records for which the hash has not previously been encountered.

If memory is a limiting factor for your dereplication jobs, see
fastq-derep.sh(3), a shell script utilizing the Unix sort command, which
automatically breaks large files into chunks so they can be sorted within
available memory.

.SH EXAMPLES
.nf
.na
xzcat file.fastq.xz | fastq-derep > file-uniq.fastq
.ad
.fi

.SH SEE ALSO

fastq2tsv(1), fastq-derep.sh(1)
