blt.o: blt.c
	${CC} -c ${CFLAGS} blt.c

chrom-lens.o: chrom-lens.c
	${CC} -c ${CFLAGS} chrom-lens.c

ensemblid2gene.o: ensemblid2gene.c
	${CC} -c ${CFLAGS} ensemblid2gene.c

extract-seq.o: extract-seq.c
	${CC} -c ${CFLAGS} extract-seq.c

fasta2seq.o: fasta2seq.c
	${CC} -c ${CFLAGS} fasta2seq.c

